# Generated by Django 5.2.13 on 2026-04-27 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='note_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'category'], name='note_user_category_idx'),
        ),
    ]
